server:
  port: 8081

spring:
  mvc:
    servlet:
      path: /api
  application:
    name: high-concurrent-likes
  data:
    redis:
      database: 0
      password: 123456
      host: 127.0.0.1
      port: 6379
      timeout: 5000
  # Redis 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/like_storm?characterEncoding=utf8
  # Pulsar 配置
  pulsar:
    client:
      service-url: pulsar://192.168.193.101:6650
    admin:
      service-url: http://192.168.193.101:8080

# spring-doc 接口文档
springdoc:
  api-docs:
    enabled: true # 是否启用接口文档
knife4j:
  enable: true # 是否启用 knife4j 增强,如果只是使用 knife4j 的 UI,则可以关闭


# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
